# Generated by Django 6.0.1 on 2026-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCv', '0005_profile_address_profile_contact_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Unknown Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='No phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
    ]
